# Numpy (Numerical Python)

## Install Numpy

In [1]:
!pip install numpy

## Importing Numpy

In [2]:
import numpy as np

## Using Numpy

In [3]:
#creating a vector.
vector = np.array([3,2,1])

In [4]:
vector

array([3, 2, 1])

In [5]:
#creating a matrix
matrix = np.array([[1,2,3],[4,5,6]])

In [6]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#Creating a tensor
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]],
                   [[9,10],[11,12]]])
tensor

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [8]:
%whos

Variable   Type       Data/Info
-------------------------------
matrix     ndarray    2x3: 6 elems, type `int64`, 48 bytes
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
tensor     ndarray    3x2x2: 12 elems, type `int64`, 96 bytes
vector     ndarray    3: 3 elems, type `int64`, 24 bytes


## ndarray
n = natural <br>
d = dimensions <br>
array = array <br>

In [9]:
#1D-Array or Vector
oneD = np.array([1,2,3])
oneD

array([1, 2, 3])

In [10]:
type(oneD)

numpy.ndarray

In [11]:
oneD.shape

(3,)

In [12]:
#2D-Array or Matrix
twoD = np.array([[1,2,3],[4,5,6]])
twoD

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
type(twoD)

numpy.ndarray

In [14]:
twoD.shape

(2, 3)

In [15]:
#3D-Array or Tensor
threeD = np.array([[[1,2,3]],
                   [[4,5,6]],
                   [[7,8,9]]])
threeD

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [16]:
type(threeD)

numpy.ndarray

In [17]:
threeD.shape

(3, 1, 3)

### Array vs List

In [18]:
ml = [[1,2,3],[4,5,6]]
ml

[[1, 2, 3], [4, 5, 6]]

In [19]:
ma = np.array([[1,2,3],[3,4,5]])
ma

array([[1, 2, 3],
       [3, 4, 5]])

In [20]:
len(ml),ma.shape

(2, (2, 3))

In [21]:
mlt = ml[0] + ml[1]
mat = ma[0] + ml[1]
mlt,mat

([1, 2, 3, 4, 5, 6], array([5, 7, 9]))

## Indexing

### Declaring Array

In [22]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

### Specific Values

In [23]:
array[0]

array([1, 2, 3])

In [24]:
array[1]

array([4, 5, 6])

In [25]:
array[0][0]

1

In [26]:
array[0][1]

2

In [27]:
array[1][1]

5

In [28]:
array[1,0]

4

In [29]:
array[1,2]

6

In [30]:
#Interval Index
array[:,1]

array([2, 5])

### Negative indeces

In [31]:
arrayb = np.array([1,2,3,4,5])
arrayb

array([1, 2, 3, 4, 5])

In [32]:
arrayb[-1]

5

In [33]:
arrayb[-5]

1

### Reverse the values


In [34]:
arrayb[::-1]

array([5, 4, 3, 2, 1])

### Assigning Values

In [35]:
arc = np.array([[1,2,3],[4,5,6]])
arc

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arc[0,1] = 3
arc

array([[1, 3, 3],
       [4, 5, 6]])

In [37]:
arc[0]= 0
arc

array([[0, 0, 0],
       [4, 5, 6]])

In [38]:
arc[:,0]=1
arc

array([[1, 0, 0],
       [1, 5, 6]])

In [39]:
lista = [4,5,6]
arc[0] = lista
arc

array([[4, 5, 6],
       [1, 5, 6]])

In [40]:
arc[:] = 1
arc

array([[1, 1, 1],
       [1, 1, 1]])

### Elementwise Properties.

In [41]:
el = np.array([[1,2,3,4],[5,6,7,8]])
el

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
el + 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [43]:
el - 2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [44]:
el * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [45]:
el / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [46]:
el ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [47]:
el // 2

array([[0, 1, 1, 2],
       [2, 3, 3, 4]])

In [48]:
ela = np.array([[1,2,3,4],[6,7,8,9]])
elb = np.array([11,12,13,14])
ela,elb

(array([[1, 2, 3, 4],
        [6, 7, 8, 9]]),
 array([11, 12, 13, 14]))

In [49]:
ela[0] + elb

array([12, 14, 16, 18])

In [50]:
ela[1] + elb

array([17, 19, 21, 23])

In [51]:
ela + elb

array([[12, 14, 16, 18],
       [17, 19, 21, 23]])

In [52]:
elb - ela

array([[10, 10, 10, 10],
       [ 5,  5,  5,  5]])

In [53]:
ela * elb

array([[ 11,  24,  39,  56],
       [ 66,  84, 104, 126]])

### Types of data supported by NumPy

In [54]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
#set data type
arr = np.array([[1,2,3],[4,5,6]],dtype = "uint64")
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint64)

In [56]:
arr = np.array([[1,2,3],[4,5,6]],dtype = np.float16)
arr

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [57]:
arr = np.array([[1,2,3],[4,5,6]],dtype = np.complex64)
arr

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [58]:
arr = np.array([[1,2,3],[4,5,6]],dtype = np.bool_)
arr

array([[ True,  True,  True],
       [ True,  True,  True]])

In [59]:
arr = np.array([[1,2,3],[4,5,6]],dtype = np.str_)
arr

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [60]:
arr = np.array([[1,2,3123123],[4,5,6]],dtype = np.str_)
arr

array([['1', '2', '3123123'],
       ['4', '5', '6']], dtype='<U7')

## Characteristics of NumPy Functions

### Universal Functions

### Broadcasting

In [61]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [62]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [63]:
matrix_c = np.array([[1,2,3],[4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.add(array_a,matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [65]:
np.add(array_b,matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

### Type casting

In [66]:
np.add(array_a,matrix_c,dtype = np.float64)

array([[2., 4., 6.],
       [5., 7., 9.]])

### Running over an Axis

In [67]:
np.mean(matrix_c,axis = 0)

array([2.5, 3.5, 4.5])

In [68]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.mean(matrix_c,axis = 1)

array([2., 5.])

## Working with Arrays

In [70]:
matrix_a = np.array([[1,2,3],[4,5,6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

### Basic slicing

In [71]:
matrix_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
matrix_a[0:1]

array([[1, 2, 3]])

In [73]:
matrix_a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

### Stepwise Slicing

In [75]:
mb = np.array([[1,2,3,4,5,0],[8,7,6,1,2,7],[9,6,7,8,5,5]])
mb

array([[1, 2, 3, 4, 5, 0],
       [8, 7, 6, 1, 2, 7],
       [9, 6, 7, 8, 5, 5]])

In [76]:
mb[::,::]

array([[1, 2, 3, 4, 5, 0],
       [8, 7, 6, 1, 2, 7],
       [9, 6, 7, 8, 5, 5]])

In [77]:
mb[::2,::]

array([[1, 2, 3, 4, 5, 0],
       [9, 6, 7, 8, 5, 5]])

In [78]:
mb[::2,::2]


array([[1, 3, 5],
       [9, 7, 5]])

### Dimensions and the squeeze function

In [79]:
matrix = np.array([[1,2,3,4,5],[5,4,5,7,8],[9,8,3,4,5]])
matrix

array([[1, 2, 3, 4, 5],
       [5, 4, 5, 7, 8],
       [9, 8, 3, 4, 5]])

In [80]:
type(matrix[0,0])

numpy.int64

In [81]:
matrix[0,0]

1

In [82]:
type(matrix[0,0:1])

numpy.ndarray

In [83]:
matrix[0:1,0:1]

array([[1]])

In [84]:
print(matrix[0,0].shape)
print(matrix[0,0:1].shape)
print(matrix[0:1,0:1].shape)

()
(1,)
(1, 1)


In [85]:
matrix[0:1,0:1].squeeze()

array(1)

In [86]:
matrix[0:1,0:1].squeeze().shape

()

## Empty Arrays, Arrays of identical Values

### np.empty(),np.zero(),np.ones(),np.full()

In [87]:
empty = np.empty((3,3))
empty

array([[1.66828498e-316, 0.00000000e+000, 1.66907707e-316],
       [6.20718786e-159, 6.92544887e-310, 1.66912371e-316],
       [1.19719497e-046, 6.92544875e-310, 3.95252517e-322]])

In [88]:
zero = np.zeros((5,5),np.float32)
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [89]:
ones = np.ones((4,4), np.int64)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [90]:
full = np.full((3,3),"Muhamad")
full

array([['Muhamad', 'Muhamad', 'Muhamad'],
       ['Muhamad', 'Muhamad', 'Muhamad'],
       ['Muhamad', 'Muhamad', 'Muhamad']], dtype='<U7')

### _Like function

In [91]:
matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [92]:
empty_like = np.empty_like(matrix)
empty_like

array([[41538832,        0,        0,        0,        0],
       [       0,        0,        0,        0,        0],
       [       0,        0,        0,        0,        0]])

In [93]:
zero_like = np.zeros_like(matrix)
zero_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [94]:
ones_like = np.ones_like(matrix)
ones_like

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [95]:
full_like = np.full_like(matrix,5)
full_like

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

### np.arange()
`aray range`

In [96]:
arange = np.arange(10)
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
arange = np.arange(5,15)
arange

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
arange = np.arange(5,20,2.5)
arange

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5])

In [99]:
arange = np.arange(3,30,2,dtype = np.float64)
arange

array([ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25., 27.,
       29.])

In [100]:
arange = np.arange(3,30,2.5,dtype = np.int64)
arange

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

### Ramdom number

In [101]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [102]:
rg = gen(pcg())
rg.normal()

0.8888106140140547

In [103]:
rg.normal(size = 5)

array([ 0.35060632, -0.51200835,  0.3519242 , -0.72798093, -0.65891809])

In [104]:
rg.normal(size = (5,5))

array([[ 0.53348489, -0.68734899,  0.31511117,  0.61582415, -0.81871272],
       [-0.0043131 , -1.54358454,  0.40864553,  0.03235258,  1.41149489],
       [-0.55067794, -0.1528636 , -0.87298511,  1.92705674,  1.01214075],
       [-0.09268291,  1.73217917, -1.40745554,  0.29665166, -0.44132156],
       [-0.9688383 , -1.2504463 , -0.42133971,  0.01808354, -0.11178227]])

In [105]:
rg = gen(pcg(seed = 365))
rg.normal()

-0.13640898920107863

In [106]:
rg.normal(size = (5,5))

array([[ 0.09414431, -0.06300442,  1.05391641, -0.6866818 , -0.50922173],
       [-0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ,  0.65526774],
       [-0.48095012, -0.5519114 , -0.58578662, -0.98257896,  1.12378166],
       [-1.30984316, -0.04703774,  0.955272  ,  0.26071745, -0.20023668],
       [-1.50172484, -1.4929163 ,  0.96535084,  1.18694633, -0.76065577]])

### Generating integers, probabilities and random choices.

In [107]:
rg = gen(pcg(seed = 365))
rg.integers(10,size=(5,5))

array([[0, 7, 6, 7, 8],
       [6, 6, 2, 0, 6],
       [3, 0, 3, 7, 9],
       [1, 1, 8, 7, 4],
       [4, 8, 6, 4, 9]])

In [108]:
rg.integers(low = 5,high = 50, size=(5,5))

array([[ 8, 40, 36,  9, 21],
       [11, 18, 23, 27, 37],
       [26, 15, 33, 21, 29],
       [ 7, 34, 14,  6, 29],
       [37, 37, 43, 18, 12]])

In [109]:
rg.random(size = (5,5))

array([[0.72989385, 0.31220331, 0.4966964 , 0.62633289, 0.25432223],
       [0.27184357, 0.58527261, 0.47582808, 0.31213978, 0.86326571],
       [0.69308801, 0.03810334, 0.7685183 , 0.35663042, 0.10106293],
       [0.84993589, 0.33190844, 0.20269642, 0.33520176, 0.98973619],
       [0.64291474, 0.32662863, 0.61190909, 0.35667588, 0.04772906]])

In [110]:
rg.choice([4,3,2,1],size = (5,5))

array([[2, 1, 3, 2, 3],
       [4, 1, 1, 4, 1],
       [4, 1, 2, 1, 1],
       [4, 1, 3, 1, 4],
       [2, 3, 3, 4, 1]])

### Generating arrays from known distrubutins

In [111]:
rg = gen(pcg(seed = 365))
rg.poisson(size = (5,5))

array([[2, 0, 1, 1, 2],
       [1, 1, 0, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 2, 1],
       [0, 1, 0, 0, 2]])

In [112]:
rg = gen(pcg(seed = 365))
rg.poisson(lam = 10,size = (5,5))

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]])

In [113]:
rg = gen(pcg(seed = 365))
rg.binomial(n= 100,p=0.4,size = (5,5))

array([[42, 44, 30, 36, 45],
       [36, 41, 38, 42, 41],
       [35, 31, 35, 46, 29],
       [41, 41, 46, 34, 48],
       [45, 45, 45, 40, 43]])

In [114]:
rg = gen(pcg(seed = 365))
rg.logistic(loc=9,scale=1.2 ,size = (5,5))

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])

### Applications of randoms generators.

In [115]:
rg = gen(pcg(seed = 365))
a1 =rg.normal(loc=2,scale = 3,size = (1000))
a2 =rg.normal(loc=7,scale = 2,size = (1000))
a3 =rg.logistic(loc=11,scale = 3,size = (1000))
a4 =rg.exponential(scale = 4,size = (1000))
a5 =rg.geometric(p=0.7,size = (1000))

In [116]:
random_test_data = np.array([a1,a2,a3,a4,a5])
random_test_data

array([[ 1.59077303,  2.28243293,  1.81098674, ...,  0.1973629 ,
        -2.21015722,  2.91161235],
       [ 6.42174295,  8.57902322,  5.17270135, ...,  4.3465854 ,
         8.2176402 ,  7.90337695],
       [10.14698427, 15.93309953, -0.46878789, ...,  2.66485989,
        12.69328115, 11.79840961],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         2.        ,  1.        ]])

In [117]:
random_test_data.transpose()

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])

In [118]:
random_test_data.shape

(5, 1000)

In [119]:
np.savetxt("Random-data-from-Numpy.csv",random_test_data.transpose(),fmt="%s",delimiter=',')

In [120]:
 np.genfromtxt("Random-data-from-Numpy.csv",delimiter=',')

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])

## Importing data with numpy

### np.loadtxt() and np.genfromtxt()

In [121]:
lending_co_data_numeric_1 = np.loadtxt("1.1 Lending-Company-Numeric-Data.csv",delimiter = ',')
lending_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [122]:
lending_co_data_numeric_2 = np.genfromtxt("1.1 Lending-Company-Numeric-Data.csv",delimiter =',')
lending_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [123]:
np.array_equal(lending_co_data_numeric_1,lending_co_data_numeric_2)

True

In [124]:
lending_co_data_numeric_NAN = np.genfromtxt("1.3 Lending-Company-Numeric-Data-NAN.csv",delimiter = ';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [125]:
lending_co_data_numeric_NAN_2 = np.loadtxt("1.3 Lending-Company-Numeric-Data-NAN.csv",delimiter =':', dtype=np.character)
lending_co_data_numeric_NAN_2

array([b'2000;40;365;3121;4241;13621', b'2000;40;365;3061;4171;15041',
       b'1000;40;365;2160;3280;15340', ..., b';40;365;4201;5001;16600',
       b'1000;40;365;2080;3320;15600', b'2000;40;365;4601;4601;16600'],
      dtype='|S30')

In [126]:
lending_co_data_numeric_NAN_2[0] + lending_co_data_numeric_NAN_2[1]

b'2000;40;365;3121;4241;136212000;40;365;3061;4171;15041'

### Partial cleaning while importing

In [127]:
lending = np.genfromtxt("1.3 Lending-Company-Numeric-Data-NAN.csv",delimiter =';')
lending

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [128]:
lending = np.genfromtxt("1.3 Lending-Company-Numeric-Data-NAN.csv",
                        delimiter = ";",
                        skip_header = 2)
lending

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [129]:
lending = np.genfromtxt("1.3 Lending-Company-Numeric-Data-NAN.csv",
                        delimiter = ";",
                        skip_footer = 2)
lending

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [130]:
lending = np.genfromtxt("1.3 Lending-Company-Numeric-Data-NAN.csv",
                        delimiter = ";",
                        usecols = (0,1,5))
lending

array([[ 2000.,    40., 13621.],
       [ 2000.,    40., 15041.],
       [ 1000.,    40., 15340.],
       ...,
       [   nan,    40., 16600.],
       [ 1000.,    40., 15600.],
       [ 2000.,    40., 16600.]])

In [131]:
lending = np.genfromtxt("1.3 Lending-Company-Numeric-Data-NAN.csv",
                        delimiter = ";",
                        usecols = (0,1,2))
lending

array([[2000.,   40.,  365.],
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       ...,
       [  nan,   40.,  365.],
       [1000.,   40.,  365.],
       [2000.,   40.,  365.]])

In [132]:
lending = np.genfromtxt("1.3 Lending-Company-Numeric-Data-NAN.csv",
                        delimiter = ";",
                        usecols = (0,1,2),
                        skip_header = 2,
                        skip_footer = 2)
lending

array([[1000.,   40.,  365.],
       [2000.,   40.,  365.],
       [2000.,   50.,  365.],
       ...,
       [2000.,   40.,  365.],
       [2000.,   40.,  365.],
       [  nan,   40.,  365.]])

In [133]:
lending1,lending2,lending3 = np.genfromtxt("1.3 Lending-Company-Numeric-Data-NAN.csv",
                        delimiter = ";",
                        usecols = (0,1,2),
                        skip_header = 2,
                        skip_footer = 2,
                        unpack = True)
lending1,lending2,lending3

(array([1000., 2000., 2000., ..., 2000., 2000.,   nan]),
 array([40., 40., 50., ..., 40., 40., 40.]),
 array([365., 365., 365., ..., 365., 365., 365.]))

### String / Object / Numbers

In [134]:
ld_co = np.genfromtxt("3.1 lending-co-LT.csv",delimiter=",")
ld_co

array([[      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       [1.000e+00,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       [2.000e+00,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       ...,
       [1.041e+03,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       [1.042e+03,       nan,       nan, ...,       nan,       nan,
        1.560e+04],
       [1.043e+03,       nan,       nan, ...,       nan,       nan,
        1.660e+04]])

In [135]:
print(ld_co)

[[      nan       nan       nan ...       nan       nan       nan]
 [1.000e+00       nan       nan ...       nan       nan 1.660e+04]
 [2.000e+00       nan       nan ...       nan       nan 1.660e+04]
 ...
 [1.041e+03       nan       nan ...       nan       nan 1.660e+04]
 [1.042e+03       nan       nan ...       nan       nan 1.560e+04]
 [1.043e+03       nan       nan ...       nan       nan 1.660e+04]]


In [136]:
ld_co = np.genfromtxt("3.1 lending-co-LT.csv",delimiter=",",dtype = np.int32)
ld_co

array([[   -1,    -1,    -1, ...,    -1,    -1,    -1],
       [    1,    -1,    -1, ...,    -1,    -1, 16600],
       [    2,    -1,    -1, ...,    -1,    -1, 16600],
       ...,
       [ 1041,    -1,    -1, ...,    -1,    -1, 16600],
       [ 1042,    -1,    -1, ...,    -1,    -1, 15600],
       [ 1043,    -1,    -1, ...,    -1,    -1, 16600]], dtype=int32)

In [137]:
ld_co = np.genfromtxt("3.1 lending-co-LT.csv",delimiter=",",dtype = np.str_)
print(ld_co)

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


In [138]:
ld_co = np.genfromtxt("3.1 lending-co-LT.csv",delimiter=",",dtype = np.object_)
print(ld_co)

[[b'LoanID' b'StringID' b'Product' ... b'Location' b'Region'
  b'TotalPrice']
 [b'1' b'id_1' b'Product B' ... b'Location 2' b'Region 2' b'16600.0']
 [b'2' b'id_2' b'Product B' ... b'Location 3' b'' b'16600.0']
 ...
 [b'1041' b'id_1041' b'Product B' ... b'Location 23' b'Region 4'
  b'16600.0']
 [b'1042' b'id_1042' b'Product C' ... b'Location 52' b'Region 6'
  b'15600.0']
 [b'1043' b'id_1043' b'Product B' ... b'Location 142' b'Region 6'
  b'16600.0']]


In [139]:
ld_co = np.genfromtxt("3.1 lending-co-LT.csv",delimiter=",",dtype = (np.int64,np.str_,np.str_,np.str_,np.str_,np.str_,np.int64))
print(ld_co)

[(  -1, '', '', '', '', '', -1) (   1, '', '', '', '', '', -1)
 (   2, '', '', '', '', '', -1) ... (1041, '', '', '', '', '', -1)
 (1042, '', '', '', '', '', -1) (1043, '', '', '', '', '', -1)]


### np.save()

In [140]:
ld = np.genfromtxt("5.1 Lending-Company-Saving.csv",
                   delimiter = ',',
                   dtype = np.str_)
ld

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

In [141]:
np.save("Lending-Saving",ld)

In [142]:
ld_save = np.load("Lending-Saving.npy")

In [143]:
ld_save

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

In [144]:
np.equal(ld_save,ld)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

### np.savez()

In [145]:
np.savez("Landing-Savez",ld,ld_save)

In [146]:
ld_savez = np.load("Landing-Savez.npz")

In [147]:
ld_savez["arr_0"]

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

In [148]:
ld_savez["arr_1"]

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

### np.savetxt()

In [149]:
ld = np.genfromtxt("5.1 Lending-Company-Saving.csv",
                   delimiter = ",",
                   dtype = np.str_)

In [150]:
np.savetxt("Lending-Save.txt",
           ld,
           fmt = "%s",
           delimiter =",")

In [151]:
ld_txt = np.genfromtxt("Lending-Save.txt",
                       delimiter = ',',
                       dtype = np.str_)
ld_txt

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

In [152]:
ld_npy = np.load("Lending-Saving.npy")
ld_npy

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

In [153]:
np.array_equal(ld_txt,ld_npy)

True

## Statistics with NumPy

### np.mean()

In [154]:
mtx_A = np.array([[3,1,9,9,2],[4,5,2,1,3],[9,6,3,1,7]])
mtx_A

array([[3, 1, 9, 9, 2],
       [4, 5, 2, 1, 3],
       [9, 6, 3, 1, 7]])

In [155]:
np.mean(mtx_A)

4.333333333333333

In [156]:
np.mean(mtx_A[0]),np.mean(mtx_A[1]),np.mean(mtx_A[2])

(4.8, 3.0, 5.2)

In [157]:
np.mean(mtx_A[:,0]),np.mean(mtx_A[:,1]),np.mean(mtx_A[:,2])

(5.333333333333333, 4.0, 4.666666666666667)

In [158]:
np.mean(mtx_A,axis= 0),np.mean(mtx_A,axis= 1)

(array([5.33333333, 4.        , 4.66666667, 3.66666667, 4.        ]),
 array([4.8, 3. , 5.2]))

In [159]:
mtx_A.mean()

4.333333333333333

In [160]:
np.sqrt(mtx_A)

array([[1.73205081, 1.        , 3.        , 3.        , 1.41421356],
       [2.        , 2.23606798, 1.41421356, 1.        , 1.73205081],
       [3.        , 2.44948974, 1.73205081, 1.        , 2.64575131]])

In [161]:
np.mean(mtx_A,axis = 1,dtype = np.int64)

array([4, 3, 5])

### Minimun and Maximum values

In [162]:
mtx_A = np.array([[3,1,9,9,2],[4,5,2,0,3],[9,6,3,8,7]])
mtx_A

array([[3, 1, 9, 9, 2],
       [4, 5, 2, 0, 3],
       [9, 6, 3, 8, 7]])

In [163]:
np.min(mtx_A),np.min(mtx_A[0]),np.min(mtx_A[1]),np.min(mtx_A[2]),

(0, 1, 0, 3)

In [164]:
np.amin(mtx_A),np.amin(mtx_A[0]),np.amin(mtx_A[1]),np.amin(mtx_A[2]),

(0, 1, 0, 3)

In [165]:
np.minimum(mtx_A[0],mtx_A[1])

array([3, 1, 2, 0, 2])

In [166]:
np.minimum.reduce(mtx_A)

array([3, 1, 2, 0, 2])

In [167]:
np.max(mtx_A)

9

In [168]:
np.amax(mtx_A)

9

### Percentiles and Quantiles

In [169]:
mtx_A = np.array([[3,1,9,9,2],[4,5,2,0,3],[9,6,3,8,7]])
mtx_A

array([[3, 1, 9, 9, 2],
       [4, 5, 2, 0, 3],
       [9, 6, 3, 8, 7]])

In [170]:
np.ptp(mtx_A)

9

In [172]:
np.ptp(mtx_A,axis = 0),np.ptp(mtx_A,axis = 1)

(array([6, 5, 7, 9, 5]), array([8, 5, 6]))

In [174]:
np.sort(mtx_A,axis=None)

array([0, 1, 2, 2, 3, 3, 3, 4, 5, 6, 7, 8, 9, 9, 9])

In [175]:
np.percentile(mtx_A,70),np.percentile(mtx_A,60),np.percentile(mtx_A,20),

(6.799999999999999, 5.4, 2.0)

In [181]:
np.percentile(mtx_A,70,method="midpoint"),np.percentile(mtx_A,70,method="higher"),np.percentile(mtx_A,70,method="lower"),np.percentile(mtx_A,70,method="nearest"),

(6.5, 7, 6, 7)

In [184]:
np.quantile(mtx_A,0.7,method="nearest")

7